version: '3.9'

services:
  web:
    build: .
    container_name: web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    networks:
      - main
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

    networks:
      - main
    environment:
      - POSTGRES_DB=shop_django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - web

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/app/static
      - media_data:/app/media
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: on-failure
  celery_worker:
    container_name: celery_worker
    command: "celery -A core worker -l INFO"
    depends_on:
      - web
      - rabbitmq
      - db
    image: web-image
    environment:
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: on-failure
networks:
  main:

volumes:
  postgresql_data:
  static_data:
  media_data: